theme: rouge-github
markdown: kramdown
show_downloads: true
title:            "Landon"
signoff:          "Landon"
description:      "❄️“从前的那个我 如果来找现在的我 会得到很好的款待”"
name:             Landon
github:
  home: https://landodo.github.io
  about: https://landodo.github.io/about
  logo: https://landodo.github.io/logo
