theme: jekyll-theme-cayman
markdown: kramdown
show_downloads: true
title:            "Landon"
signoff:          "Landon"
description:      "# NEVER SETTLE #"
name:             Landon
github:
  home: https://landodo.github.io
  about: https://landodo.github.io/about