theme: jekyll-theme-cayman
title:            "Landon"
signoff:          "Landon"
description:      "# University of Chinese Academy of Sciences - Chengdu Institute of Computer Application"
name:             Landon
links:
  - name:         Home
    url:          /
    external:     false
  - name:         Contents
    url:          /contents
    external:     false
  - name:         About
    url:          /about
    external:     false
  - name:         GitHub
    url:          https://github.com/donngdev
    external:     true
